### ISSUE TITLE
Error when docs reference to external file

### ISSUE THREAD

**Issue by 3mp3ri0r** [koumoul-dev/openapi-viewer#10]
I've tried simple docs that contain reference to external file. The viewer only show blank page and in console show some error like this:
![koumol-error](https://user-images.githubusercontent.com/3140815/41495308-53cf232e-714e-11e8-808d-12e560588afb.png)

This is the main file: [Main](https://gist.githubusercontent.com/3mp3ri0r/bdc695e63828688bfe389b6f4d090021/raw/bab85dc32c3f7e97d67bb34f0053df48fc406985/cobaRefExternal.json)

This is the external file: [External](https://gist.githubusercontent.com/3mp3ri0r/307fa6314ad5a9e31a8ac9f04273a272/raw/1c7e1ba47f6a57861a41320a6f2a962352f2ac6a/membershipGetJson.json)

Any update or recomendation will be helpful since only koumol can intrepet ref with example correctly in OAS 3. Thanks.

**Comment by nicolas-bonnel** [comment]
Thanks for reporting this, we will try to address this problem as soon as possible (perhaps 1-2 weeks as we are very busy for the moment)

**Comment by nicolas-bonnel** [comment]
Fixed in last version. See [your example](https://koumoul.com/openapi-viewer/?url=https://gist.githubusercontent.com/3mp3ri0r/bdc695e63828688bfe389b6f4d090021/raw/bab85dc32c3f7e97d67bb34f0053df48fc406985/cobaRefExternal.json&proxy=false)
