### ISSUE TITLE
Can not show multiple example (examples) everywhere

### ISSUE THREAD

**Issue by 3mp3ri0r** [koumoul-dev/openapi-viewer#12]
Hi there. `openapi-viewer` can not show example when there is multiple examples defined by `examples` parameter everywhere, including parameters, requestBodies, responses, and schema. Hope it will be fixed soon. Thank you.

**Comment by nicolas-bonnel** [comment]
Hi,
Can you provide an API file that raises this problems ?

Thanks.

**Comment by nicolas-bonnel** [comment]
Thanks for the sample file. I don't have a lot of time but i'll try to make a release addressing this and #10 next week

**Comment by 3mp3ri0r** [comment]
Nice @nicolas-bonnel. Thank you.

**Comment by nicolas-bonnel** [comment]
I just released the 0.7.0 version and deployed it on our site. Examples in your link are now displayed.

**Comment by 3mp3ri0r** [comment]
Amazing update @nicolas-bonnel. Thank you so much!
