### ISSUE TITLE
JS errors loading simple OpenAPI 3.0.0 spec

### ISSUE THREAD

**Issue by gunsch** [koumoul-dev/openapi-viewer#5]
Steps:
(1) Take this YAML file https://github.com/darrelmiller/cowpi/blob/master/COW1.0.0.yml
(2) Convert to JSON (uploaded as [api.json.txt](https://github.com/koumoul-dev/openapi-viewer/files/1432423/api.json.txt))
(3) Host this JSON and provide a copy to locally running "openapi-viewer" instance
(4) Confirm that the JSON is being loaded correctly (using Chrome network inspector), but rendering fails.
(5) JS Console has a pile of JS errors, starting from this:

```
[Vue warn]: Error in render function: "TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked."

found in

---> <OpenApi>
       <App>
         <Root>

```
(context: trying this out at APIStrat, recommended on the OpenAPI IMPLEMENTATIONS.MD file)

**Comment by nicolas-bonnel** [comment]
Thanks for your feedback. koumoul-dev/vue-openapi@2f0b0bb1ffdfcf81992aa0d353b0ef612c6d9e02 in the [vue-openapi](https://github.com/koumoul-dev/vue-openapi/) component should fix that

**Comment by nicolas-bonnel** [comment]
This now seems to work correctly : https://koumoul.com/openapi-viewer/?url=https://github.com/koumoul-dev/openapi-viewer/files/1432423/api.json.txt&proxy=true
