### ISSUE TITLE
Path Level Parameters

### ISSUE THREAD

**Issue by Nessworthy** [koumoul-dev/openapi-viewer#8]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#pathItemObject

Path objects support defining global parameters for all operations it has. The openapi viewer displays this as if it's a separate operation (e.g. GET /foo, POST /foo, PARAMETERS /foo), and the parameters aren't added to the normal operations.

**Comment by nicolas-bonnel** [comment]
Hi,

We will take care of this problem in the next release. Could you provide us an openapi json file with global parameters on a path object ?

**Comment by albanm** [comment]
The 0.6.0 docker image is currently building and should be available soon with this functionality.

I'm closing this issue for now, reopen if something is not working.
