### ISSUE TITLE
Open API viewer redirects to koumoul.com

### ISSUE THREAD

**Issue by bouchezb** [koumoul-dev/openapi-viewer#9]
Hi, 

I have a docker container with open-api viewer, integrated in a webapp.
UI works fine, but when i refresh the page containing API Doc, i am redirected to koumoul.com

Steps to reproduce
```
https://my.website.fr/api-doc
+ F5
= https://my.website.fr/api-doc/?url=https://koumoul.com/s/geocoder/api/v1/api-docs.json&proxy=false
```

This do not happen in dev configuration.
I suspect an issue with NGINX. Do you know if there are some specific settings to use with NGINX ?

Regards.

**Comment by nicolas-bonnel** [comment]
You're right, that's a proxy configuration problem. I think your application is at the root of your domain and it has a page that has the same url that the one of the api-doc viewer. You should expose your the api-viewer on another path, free of conflict.
